# This workflow will build an Arch Linux ISO file with the commit on it

name: Runs Qemu test case pci_emulation

on:
  workflow_run:
    workflows: ["Build Arch ISO with ArchInstall Commit"]
    branches: [main, test-cases]
    types:
      - completed
  push:
    branches:
      - master
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.editorconfig'
      - '**.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'PKGBUILD'
  release:
    types:
      - created

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: Arch Live ISO
          path: /tmp/archlive/out/*.iso
      - run: cd tests/qemu
      - run: echo '' > serial.log
      - run: pwd
      - run: tree
      - uses: actions/upload-artifact@v4
        with:
          name: archtest-pci_emulation
          path: ./demo.cast
