name: Runs Qemu test case pci_emulation

# This job is callewd from iso-build
on:
  workflow_call:

jobs:
  run-qemu:
    name: qemu testbench
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: Arch Live ISO
          path: ./_work/iso/
      - run: cd tests/qemu
      - run: echo '' > serial.log
      # Generate a .screenrc that will auto-run the test
      # as well as record it for publishing using asciinema.
      - run: |
            cat <<EOF >> .screenrc_test
            startup_message off
            chdir tests/qemu
            screen 0 python run_test.py
            split
            focus down
            resize 24
            screen 1 asciinema rec demo.cast --overwrite -c "tail -f serial.log"
            EOF
      - run: pwd
      - run: cp /usr/share/ovmf/x64/OVMF_VARS.fd ./OVMF_VARS.fd
      - run: tree
      - run: cat .screenrc_test
      - run: script /dev/null -c "screen -c .screenrc_test"
      - uses: actions/upload-artifact@v4
        with:
          name: archtest-pci_emulation
          path: ./tests/qemu/demo.cast
